### ISSUE TITLE
Add support for front end tests in build

### ISSUE THREAD

**Issue by skarsaune** [hawtio/hawtio-jmx#32] opened 2017-12-12 10:10 UTC
I would like to include some regression tests, preferrably in typescript. Could someone experienced with front end set it up, or advise on how to best do it?
Cheers!

**Comment by tadayosi** [comment] 2017-12-18 03:29
I totally agree that hawtio v2 should have some test suite.

@akieling @astefanutti Do you guys have any ideas?  Should we use Karma, Jasmine, Protractor, or anything else?

**Comment by astefanutti** [comment] 2017-12-18 09:11
That'd be awesome to have some tests to catch regressions. We have experienced Karma and Jasmine on other projects and that seems to do the job.

**Comment by abkieling** [comment] 2017-12-18 11:46
Karma is great to run unit tests. It's used in @hawtio/core and we should set it up on other repositories as well. Protractor is good to run e2e tests (UI driven tests) using Selenium/WebDriver but since the release of [headless](https://developers.google.com/web/updates/2017/04/headless-chrome) Chrome and the [Puppeteer](https://github.com/GoogleChrome/puppeteer) library, I've seen some people moving to Puppeteer. Here is a [blog post](https://ropig.com/blog/end-end-tests-dont-suck-puppeteer/) talking about the two options.
To run e2e tests, we would need to set up a jolokia endpoint before running the tests. Something like Docker Compose might help with that, right?
Also, It would be important to have the tests running on CircleCI. We are currently using CircleCI v1 but it would be a good opportunity to move to CircleCI v2.

**Closed as completed** 2019-03-18 15:53 UTC
Labels: help wanted
